require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'Respiree' do
  use_unimodules!(exclude: ['expo-splash-screen'])
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  target 'RespireeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #  flipper_post_install(installer)
  # end
end

target 'Respiree-tvOS' do
  # Pods for Respiree-tvOS

  target 'Respiree-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
